
"@context":

ontologies:

## HCAO

  - id: hcao
    preferredPrefix: HCAO
    title: Human Cell Atlas Ontology
    description: Application ontology for human cell types, anatomy and development stages for the Human Cell Atlas
    uri: http://ontology.data.humancellatlas.org/ontologies/hcao
    base_uri:
      - http://ontology.data.humancellatlas.org/ontologies/HCA_
      - http://purl.obolibrary.org/obo/UBERON_
      - http://purl.obolibrary.org/obo/CL_
      - http://purl.obolibrary.org/obo/HsapDv_    
    synonym_property:
      - http://www.geneontology.org/formats/oboInOwl#hasExactSynonym
    definition_property:
      - http://purl.obolibrary.org/obo/IAO_0000115
    reasoner: EL
    oboSlims: false
    ontology_purl : file:///opt/ols/ontologies/hcao.owl

## EFO

  - id: efo
    preferredPrefix: EFO
    title: Experimental Factor Ontology (HCA subset)
    uri: http://ontology.data.humancellatlas.org/ontologies/efo
    description: "Subset of the EMBL-EBI Experimental Factor Ontology covering experimental processes, instruments, biological macromolecules, organisms/strains, protocols and units built for the HCA project."
    homepage: http://www.ebi.ac.uk/efo
    mailing_list: efo-users@lists.sourceforge.net
    definition_property:
      - http://www.ebi.ac.uk/efo/definition
    synonym_property:
      - http://www.ebi.ac.uk/efo/alternative_term
    hierarchical_property:
      - http://purl.obolibrary.org/obo/BFO_0000050
      - http://purl.obolibrary.org/obo/RO_0002202
    hidden_property:
      - http://www.ebi.ac.uk/efo/has_flag
    base_uri:
      - http://www.ebi.ac.uk/efo/EFO_
    reasoner: OWL2
    oboSlims: false
    ontology_purl: file:///opt/ols/ontologies/efo_slim.owl

## MONDO

  - id: mondo
    preferredPrefix: MONDO
    title: Monarch Disease Ontology
    uri: http://purl.obolibrary.org/obo/mondo.owl
    description: "An ontology that harmonizes multiple disease resources."
    homepage: https://monarchinitiative.org
    mailing_list: https://github.com/monarch-initiative/monarch-disease-ontology/issues
    base_uri:
      - hhttp://purl.obolibrary.org/obo/MONDO_
    reasoner: None
    oboSlims: false
    ontology_purl: http://purl.obolibrary.org/obo/mondo.obo


## FBBI

  - id: fbbi
    preferredPrefix: FBbi
    title: Biological Imaging Methods Ontology - HCAO subset
    uri: http://purl.obolibrary.org/obo/mondo.owl
    description: "A structured controlled vocabulary of sample
    preparation, visualization and imaging methods used in biomedical
    research."
    homepage: http://cellimagelibrary.org/home
    base_uri:
      - hhttp://purl.obolibrary.org/obo/FBbi_
    reasoner: None
    oboSlims: false
    ontology_purl: file:///opt/ols/ontologies/fbbi_hcao.owl

## HAncestrO

  - id: hancestro
    preferredPrefix: HANCESTRO
    title: Human Ancestry Ontology
    uri: http://purl.obolibrary.org/obo/hancestro.owl
    description: "The Human Ancestry Ontology (Hancestro) provides a systematic description of the ancestry concepts used in the NHGRI-EBI Catalog of published genome
wide association studies. It includes a list of countries, regions and major areas (essentially continents), as well as a fairly exhaustive list of country or region-specific ancestral groups, uncategorised ancestral groups and population isolates."
    homepage: https://github.com/EBISPOT/ancestro/
    mailing_list:
    definition_property:
      - http://purl.obolibrary.org/obo/IAO_0000115
    synonym_property:
      - http://purl.obolibrary.org/obo/IAO_0000118
    hierarchical_property:
      - http://purl.obolibrary.org/obo/BFO_0000050
    base_uri:
      - http://purl.obolibrary.org/obo/HANCESTRO_
    oboSlims: false
    reasoner: OWL2
    ontology_purl : https://raw.githubusercontent.com/EBISPOT/ancestro/master/hancestro.owl


## EDAM

  - id: edam
    preferredPrefix: EDAM
    title: Bioinformatics operations, data types, formats, identifiers and topics
    uri: https://www.ebi.ac.uk/ols/api/ontologies/edam
    description: "EDAM is a simple ontology of well established, familiar concepts that are prevalent within bioinformatics, including types of data and data identifiers, data formats, operations and topics. EDAM provides a set of terms with synonyms and definitions - organised into an intuitive hierarchy for convenient use."
    homepage: http://edamontology.org/
    definition_property:
      - http://www.geneontology.org/formats/oboInOwl#hasDefinition
    synonym_property:
      - http://www.geneontology.org/formats/oboInOwl#hasNarrowSynonym
      - http://www.geneontology.org/formats/oboInOwl#hasExactSynonym
    hierarchical_property:
      - http://purl.obolibrary.org/obo/BFO_0000050
    base_uri:
      - http://edamontology.org/data_
      - http://edamontology.org/identifier_
      - http://edamontology.org/topic_
      - http://edamontology.org/format_
    oboSlims: false
    reasoner: NONE
    ontology_purl : http://edamontology.org/EDAM.owl

