PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX clrel: <http://purl.obolibrary.org/obo/cl#>
PREFIX uberonrel: <http://purl.obolibrary.org/obo/uberon/core#>
PREFIX efo: <http://www.ebi.ac.uk/efo/EFO_#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>
SELECT ?term 
WHERE {
  ?term oboInOwl:inSubset ?subset .
  VALUES ?subset { clrel:added_for_HCA uberonrel:added_for_HCA efo:0010944}
}